export const queryKeys = {
  movie: (slug: string) => ["movie", slug],
  movieAll: ["movie"],
  comments: (movieSlug: string) => ["comments", movieSlug],
  tag: (slug: string) => ["tag", slug],
  tagMovies: (slug: string) => ["tag-movies", slug],
  tags: ["tags"],
  search: (q: string) => ["search", q],
  shorts: ["shorts"],
  watchlist: ["watchlist"],
  homeWatchlist: ["home-watchlist"],
  health: ["health"],
  adminMovies: ["admin-movies"],
  adminTags: ["admin-tags"],
  adminTagsSelect: ["admin-tags-select"],
  adminUsers: ["admin-users"],
  adminRequests: ["admin-requests"],
  adminReports: ["admin-reports"],
  adminFeatured: ["admin-featured"],
  adminStats: ["admin-stats"],
  adminRecentSignups: ["admin-recent-signups"],
  adminMostFavorited: ["admin-most-favorited"],
} as const;
